/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminTopupsRouteImport } from './routes/admin/topups'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopAlertsRouteImport } from './routes/shop/alerts'
import { Route as ShopBoxRouteImport } from './routes/shop/box'
import { Route as ShopCatalogRouteImport } from './routes/shop/catalog'
import { Route as ShopClaimsRouteImport } from './routes/shop/claims'
import { Route as ShopHistoryRouteImport } from './routes/shop/history'
import { Route as ShopPrivacyRouteImport } from './routes/shop/privacy'
import { Route as ShopProfileRouteImport } from './routes/shop/profile'
import { Route as ShopSettingsRouteImport } from './routes/shop/settings'
import { Route as ShopTopupRouteImport } from './routes/shop/topup'
import { Route as ShopWheelRouteImport } from './routes/shop/wheel'
import { Route as AdminPaymentsReconciliationRouteImport } from './routes/admin/payments/reconciliation'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiJobsRunRouteImport } from './routes/api/jobs/run'
import { Route as ApiMediaIdRouteImport } from './routes/api/media/$id'
import { Route as ApiSlipVerifyRouteImport } from './routes/api/slip/verify'
import { Route as ShopProductIdRouteImport } from './routes/shop/product/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopupsRoute = AdminTopupsRouteImport.update({
  id: '/topups',
  path: '/topups',
  getParentRoute: () => AdminRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAlertsRoute = ShopAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBoxRoute = ShopBoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCatalogRoute = ShopCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ShopRoute,
} as any)
const ShopClaimsRoute = ShopClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => ShopRoute,
} as any)
const ShopHistoryRoute = ShopHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPrivacyRoute = ShopPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProfileRoute = ShopProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSettingsRoute = ShopSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTopupRoute = ShopTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => ShopRoute,
} as any)
const ShopWheelRoute = ShopWheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => ShopRoute,
} as any)
const AdminPaymentsReconciliationRoute =
  AdminPaymentsReconciliationRouteImport.update({
    id: '/payments/reconciliation',
    path: '/payments/reconciliation',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRunRoute = ApiJobsRunRouteImport.update({
  id: '/api/jobs/run',
  path: '/api/jobs/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlipVerifyRoute = ApiSlipVerifyRouteImport.update({
  id: '/api/slip/verify',
  path: '/api/slip/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/shop/alerts': typeof ShopAlertsRoute
  '/shop/box': typeof ShopBoxRoute
  '/shop/catalog': typeof ShopCatalogRoute
  '/shop/claims': typeof ShopClaimsRoute
  '/shop/history': typeof ShopHistoryRoute
  '/shop/privacy': typeof ShopPrivacyRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/topup': typeof ShopTopupRoute
  '/shop/wheel': typeof ShopWheelRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/payments/reconciliation': typeof AdminPaymentsReconciliationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/run': typeof ApiJobsRunRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/slip/verify': typeof ApiSlipVerifyRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/shop/alerts': typeof ShopAlertsRoute
  '/shop/box': typeof ShopBoxRoute
  '/shop/catalog': typeof ShopCatalogRoute
  '/shop/claims': typeof ShopClaimsRoute
  '/shop/history': typeof ShopHistoryRoute
  '/shop/privacy': typeof ShopPrivacyRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/topup': typeof ShopTopupRoute
  '/shop/wheel': typeof ShopWheelRoute
  '/shop': typeof ShopIndexRoute
  '/admin/payments/reconciliation': typeof AdminPaymentsReconciliationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/run': typeof ApiJobsRunRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/slip/verify': typeof ApiSlipVerifyRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/shop/alerts': typeof ShopAlertsRoute
  '/shop/box': typeof ShopBoxRoute
  '/shop/catalog': typeof ShopCatalogRoute
  '/shop/claims': typeof ShopClaimsRoute
  '/shop/history': typeof ShopHistoryRoute
  '/shop/privacy': typeof ShopPrivacyRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/topup': typeof ShopTopupRoute
  '/shop/wheel': typeof ShopWheelRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/payments/reconciliation': typeof AdminPaymentsReconciliationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/run': typeof ApiJobsRunRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/slip/verify': typeof ApiSlipVerifyRoute
  '/shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/rent'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/topups'
    | '/shop/alerts'
    | '/shop/box'
    | '/shop/catalog'
    | '/shop/claims'
    | '/shop/history'
    | '/shop/privacy'
    | '/shop/profile'
    | '/shop/settings'
    | '/shop/topup'
    | '/shop/wheel'
    | '/shop/'
    | '/admin/payments/reconciliation'
    | '/api/auth/$'
    | '/api/jobs/run'
    | '/api/media/$id'
    | '/api/slip/verify'
    | '/shop/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/rent'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/topups'
    | '/shop/alerts'
    | '/shop/box'
    | '/shop/catalog'
    | '/shop/claims'
    | '/shop/history'
    | '/shop/privacy'
    | '/shop/profile'
    | '/shop/settings'
    | '/shop/topup'
    | '/shop/wheel'
    | '/shop'
    | '/admin/payments/reconciliation'
    | '/api/auth/$'
    | '/api/jobs/run'
    | '/api/media/$id'
    | '/api/slip/verify'
    | '/shop/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/rent'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/topups'
    | '/shop/alerts'
    | '/shop/box'
    | '/shop/catalog'
    | '/shop/claims'
    | '/shop/history'
    | '/shop/privacy'
    | '/shop/profile'
    | '/shop/settings'
    | '/shop/topup'
    | '/shop/wheel'
    | '/shop/'
    | '/admin/payments/reconciliation'
    | '/api/auth/$'
    | '/api/jobs/run'
    | '/api/media/$id'
    | '/api/slip/verify'
    | '/shop/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RentRoute: typeof RentRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJobsRunRoute: typeof ApiJobsRunRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiSlipVerifyRoute: typeof ApiSlipVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topups': {
      id: '/admin/topups'
      path: '/topups'
      fullPath: '/admin/topups'
      preLoaderRoute: typeof AdminTopupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/alerts': {
      id: '/shop/alerts'
      path: '/alerts'
      fullPath: '/shop/alerts'
      preLoaderRoute: typeof ShopAlertsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/box': {
      id: '/shop/box'
      path: '/box'
      fullPath: '/shop/box'
      preLoaderRoute: typeof ShopBoxRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/catalog': {
      id: '/shop/catalog'
      path: '/catalog'
      fullPath: '/shop/catalog'
      preLoaderRoute: typeof ShopCatalogRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/claims': {
      id: '/shop/claims'
      path: '/claims'
      fullPath: '/shop/claims'
      preLoaderRoute: typeof ShopClaimsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/history': {
      id: '/shop/history'
      path: '/history'
      fullPath: '/shop/history'
      preLoaderRoute: typeof ShopHistoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/privacy': {
      id: '/shop/privacy'
      path: '/privacy'
      fullPath: '/shop/privacy'
      preLoaderRoute: typeof ShopPrivacyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/profile': {
      id: '/shop/profile'
      path: '/profile'
      fullPath: '/shop/profile'
      preLoaderRoute: typeof ShopProfileRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/settings': {
      id: '/shop/settings'
      path: '/settings'
      fullPath: '/shop/settings'
      preLoaderRoute: typeof ShopSettingsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/topup': {
      id: '/shop/topup'
      path: '/topup'
      fullPath: '/shop/topup'
      preLoaderRoute: typeof ShopTopupRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/wheel': {
      id: '/shop/wheel'
      path: '/wheel'
      fullPath: '/shop/wheel'
      preLoaderRoute: typeof ShopWheelRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/payments/reconciliation': {
      id: '/admin/payments/reconciliation'
      path: '/payments/reconciliation'
      fullPath: '/admin/payments/reconciliation'
      preLoaderRoute: typeof AdminPaymentsReconciliationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/run': {
      id: '/api/jobs/run'
      path: '/api/jobs/run'
      fullPath: '/api/jobs/run'
      preLoaderRoute: typeof ApiJobsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slip/verify': {
      id: '/api/slip/verify'
      path: '/api/slip/verify'
      fullPath: '/api/slip/verify'
      preLoaderRoute: typeof ApiSlipVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTopupsRoute: typeof AdminTopupsRoute
  AdminPaymentsReconciliationRoute: typeof AdminPaymentsReconciliationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTopupsRoute: AdminTopupsRoute,
  AdminPaymentsReconciliationRoute: AdminPaymentsReconciliationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopRouteChildren {
  ShopAlertsRoute: typeof ShopAlertsRoute
  ShopBoxRoute: typeof ShopBoxRoute
  ShopCatalogRoute: typeof ShopCatalogRoute
  ShopClaimsRoute: typeof ShopClaimsRoute
  ShopHistoryRoute: typeof ShopHistoryRoute
  ShopPrivacyRoute: typeof ShopPrivacyRoute
  ShopProfileRoute: typeof ShopProfileRoute
  ShopSettingsRoute: typeof ShopSettingsRoute
  ShopTopupRoute: typeof ShopTopupRoute
  ShopWheelRoute: typeof ShopWheelRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAlertsRoute: ShopAlertsRoute,
  ShopBoxRoute: ShopBoxRoute,
  ShopCatalogRoute: ShopCatalogRoute,
  ShopClaimsRoute: ShopClaimsRoute,
  ShopHistoryRoute: ShopHistoryRoute,
  ShopPrivacyRoute: ShopPrivacyRoute,
  ShopProfileRoute: ShopProfileRoute,
  ShopSettingsRoute: ShopSettingsRoute,
  ShopTopupRoute: ShopTopupRoute,
  ShopWheelRoute: ShopWheelRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RentRoute: RentRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJobsRunRoute: ApiJobsRunRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiSlipVerifyRoute: ApiSlipVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
