/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopAlertsRouteImport } from './routes/shop/alerts'
import { Route as ShopBoxRouteImport } from './routes/shop/box'
import { Route as ShopCatalogRouteImport } from './routes/shop/catalog'
import { Route as ShopClaimsRouteImport } from './routes/shop/claims'
import { Route as ShopHistoryRouteImport } from './routes/shop/history'
import { Route as ShopProfileRouteImport } from './routes/shop/profile'
import { Route as ShopSettingsRouteImport } from './routes/shop/settings'
import { Route as ShopTopupRouteImport } from './routes/shop/topup'
import { Route as ShopWheelRouteImport } from './routes/shop/wheel'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSlipVerifyRouteImport } from './routes/api/slip/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAlertsRoute = ShopAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBoxRoute = ShopBoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCatalogRoute = ShopCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ShopRoute,
} as any)
const ShopClaimsRoute = ShopClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => ShopRoute,
} as any)
const ShopHistoryRoute = ShopHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProfileRoute = ShopProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSettingsRoute = ShopSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTopupRoute = ShopTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => ShopRoute,
} as any)
const ShopWheelRoute = ShopWheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => ShopRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlipVerifyRoute = ApiSlipVerifyRouteImport.update({
  id: '/api/slip/verify',
  path: '/api/slip/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/alerts': typeof ShopAlertsRoute
  '/shop/box': typeof ShopBoxRoute
  '/shop/catalog': typeof ShopCatalogRoute
  '/shop/claims': typeof ShopClaimsRoute
  '/shop/history': typeof ShopHistoryRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/topup': typeof ShopTopupRoute
  '/shop/wheel': typeof ShopWheelRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/slip/verify': typeof ApiSlipVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/shop/alerts': typeof ShopAlertsRoute
  '/shop/box': typeof ShopBoxRoute
  '/shop/catalog': typeof ShopCatalogRoute
  '/shop/claims': typeof ShopClaimsRoute
  '/shop/history': typeof ShopHistoryRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/topup': typeof ShopTopupRoute
  '/shop/wheel': typeof ShopWheelRoute
  '/shop': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/slip/verify': typeof ApiSlipVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/rent': typeof RentRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/alerts': typeof ShopAlertsRoute
  '/shop/box': typeof ShopBoxRoute
  '/shop/catalog': typeof ShopCatalogRoute
  '/shop/claims': typeof ShopClaimsRoute
  '/shop/history': typeof ShopHistoryRoute
  '/shop/profile': typeof ShopProfileRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/topup': typeof ShopTopupRoute
  '/shop/wheel': typeof ShopWheelRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/slip/verify': typeof ApiSlipVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/rent'
    | '/shop'
    | '/shop/alerts'
    | '/shop/box'
    | '/shop/catalog'
    | '/shop/claims'
    | '/shop/history'
    | '/shop/profile'
    | '/shop/settings'
    | '/shop/topup'
    | '/shop/wheel'
    | '/shop/'
    | '/api/auth/$'
    | '/api/slip/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/rent'
    | '/shop/alerts'
    | '/shop/box'
    | '/shop/catalog'
    | '/shop/claims'
    | '/shop/history'
    | '/shop/profile'
    | '/shop/settings'
    | '/shop/topup'
    | '/shop/wheel'
    | '/shop'
    | '/api/auth/$'
    | '/api/slip/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/rent'
    | '/shop'
    | '/shop/alerts'
    | '/shop/box'
    | '/shop/catalog'
    | '/shop/claims'
    | '/shop/history'
    | '/shop/profile'
    | '/shop/settings'
    | '/shop/topup'
    | '/shop/wheel'
    | '/shop/'
    | '/api/auth/$'
    | '/api/slip/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  RentRoute: typeof RentRoute
  ShopRoute: typeof ShopRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSlipVerifyRoute: typeof ApiSlipVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/alerts': {
      id: '/shop/alerts'
      path: '/alerts'
      fullPath: '/shop/alerts'
      preLoaderRoute: typeof ShopAlertsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/box': {
      id: '/shop/box'
      path: '/box'
      fullPath: '/shop/box'
      preLoaderRoute: typeof ShopBoxRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/catalog': {
      id: '/shop/catalog'
      path: '/catalog'
      fullPath: '/shop/catalog'
      preLoaderRoute: typeof ShopCatalogRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/claims': {
      id: '/shop/claims'
      path: '/claims'
      fullPath: '/shop/claims'
      preLoaderRoute: typeof ShopClaimsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/history': {
      id: '/shop/history'
      path: '/history'
      fullPath: '/shop/history'
      preLoaderRoute: typeof ShopHistoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/profile': {
      id: '/shop/profile'
      path: '/profile'
      fullPath: '/shop/profile'
      preLoaderRoute: typeof ShopProfileRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/settings': {
      id: '/shop/settings'
      path: '/settings'
      fullPath: '/shop/settings'
      preLoaderRoute: typeof ShopSettingsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/topup': {
      id: '/shop/topup'
      path: '/topup'
      fullPath: '/shop/topup'
      preLoaderRoute: typeof ShopTopupRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/wheel': {
      id: '/shop/wheel'
      path: '/wheel'
      fullPath: '/shop/wheel'
      preLoaderRoute: typeof ShopWheelRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slip/verify': {
      id: '/api/slip/verify'
      path: '/api/slip/verify'
      fullPath: '/api/slip/verify'
      preLoaderRoute: typeof ApiSlipVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopAlertsRoute: typeof ShopAlertsRoute
  ShopBoxRoute: typeof ShopBoxRoute
  ShopCatalogRoute: typeof ShopCatalogRoute
  ShopClaimsRoute: typeof ShopClaimsRoute
  ShopHistoryRoute: typeof ShopHistoryRoute
  ShopProfileRoute: typeof ShopProfileRoute
  ShopSettingsRoute: typeof ShopSettingsRoute
  ShopTopupRoute: typeof ShopTopupRoute
  ShopWheelRoute: typeof ShopWheelRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAlertsRoute: ShopAlertsRoute,
  ShopBoxRoute: ShopBoxRoute,
  ShopCatalogRoute: ShopCatalogRoute,
  ShopClaimsRoute: ShopClaimsRoute,
  ShopHistoryRoute: ShopHistoryRoute,
  ShopProfileRoute: ShopProfileRoute,
  ShopSettingsRoute: ShopSettingsRoute,
  ShopTopupRoute: ShopTopupRoute,
  ShopWheelRoute: ShopWheelRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  RentRoute: RentRoute,
  ShopRoute: ShopRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSlipVerifyRoute: ApiSlipVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
